using System;

public enum CardType
{
	None = -1,
	NoOverride,
	BuffEnhancer = 0x1A,
	Cleanse = 1,
	Cleanse_Prep = 0x20,
	Crippler = 2,
	Cryoshell,
	DashToEnemyAndChase = 0x19,
	DebuffSingleSquareScramble = 0x1D,
	EnergyLeachAoE = 4,
	EnergyGainOnEnemyHitAoE = 0x1C,
	Flash = 5,
	FlashAndRoot = 0x16,
	FlashAndStealth,
	FlashToAlly,
	KnockbackAroundSelf = 0x1B,
	RadiationInjection = 6,
	ReduceCooldown,
	ReduceCooldown_Prep = 0x1E,
	RevealArea = 0x14,
	SecondWind = 8,
	SecondWind_Prep = 0x1F,
	StarterAbilityIncrease = 9,
	StarterCritShot,
	StarterEnergyAoE,
	StarterEnergyRegen,
	StarterHealAoE,
	StarterHealthIncrease,
	StarterHealthRegen,
	StarterMovementIncrease,
	Tether,
	TurtleTech,
	Unstoppable = 0x15,
	Vampirism = 0x13
}
