using System;

public enum KeyPreference
{
	NullPreference,
	CameraCenterOnAction,
	CameraToggleAutoCenter,
	CameraPanUp,
	CameraPanDown,
	CameraPanLeft,
	CameraPanRight,
	CameraRotateClockwise,
	CameraRotateCounterClockwise,
	Ability1 = 0x64,
	Ability2,
	Ability3,
	Ability4,
	Ability5,
	Ability6,
	Ability7,
	Card1 = 0x6E,
	Card2,
	Card3,
	LockIn = 0xC8,
	CancelAction,
	CycleTarget,
	ToggleInfo,
	ToggleSystemMenu,
	ToggleHUD,
	MinimapPing,
	ToggleHUDExceptNameplates,
	ChatReply,
	ChatAll,
	ShowAllyAbilityInfo,
	AbilityRetargetingModifier,
	CycleTeam,
	TakeScreenShot,
	ToggleFPS,
	MovementWaypointModifier,
	ShowPersonalVisibility,
	ToggleSpectatorDrawMode,
	ClearSpectatorDraw,
	Unconfirm,
	Seasons_FE_Nav = 0x12C,
	Collection_FE_Nav,
	Loot_FE_Nav,
	RecruitAFriend_FE_Nav,
	Profile_FE_Nav,
	FreelancerStats_FE_Nav,
	Match_History_Replays_FE_Nav,
	Banner_FE_Nav,
	SwitchFreelancer,
	Freelancer1,
	Freelancer2,
	Freelancer3,
	Freelancer4,
	Freelancer5
}
