public enum MyMsgType : short
{
	ReplayManagerFile = 48,
	DisplayAlert = 49,
	CastAbility = 50,
	LoginRequest = 51,
	LoginResponse = 52,
	AssetsLoadedNotification = 53,
	SpawningObjectsNotification = 54,
	ClientPreparedForGameStartNotification = 55,
	ReconnectReplayStatus = 56,
	ObserverMessage = 57,
	StartResolutionPhase = 58,
	ClientResolutionPhaseCompleted = 59,
	ResolveKnockbacksForActor = 60,
	ClientAssetsLoadingProgressUpdate = 61,
	ServerAssetsLoadingProgressUpdate = 62,
	RunResolutionActionsOutsideResolve = 63,
	SingleResolutionAction = 64,
	ClientRequestTimeUpdate = 65,
	Failsafe_HurryResolutionPhase = 66,
	LeaveGameNotification = 67,
	EndGameNotification = 68,
	ServerMovementStarting = 69,
	ClientMovementPhaseCompleted = 70,
	Failsafe_HurryMovementPhase = 71,
	ClashesAtEndOfMovement = 72,
	ClientFakeActionRequest = 32000,
	ServerFakeActionResponse = 32001
}
