using System;

public enum TurnStateEnum
{
	DECIDING,
	VALIDATING_MOVE_REQUEST,
	TARGETING_ACTION,
	VALIDATING_ACTION_REQUEST,
	DECIDING_MOVEMENT,
	CONFIRMED,
	RESOLVING,
	WAITING,
	RESPAWNING,
	RESPAWNING_TAKES_ACTION,
	PICKING_RESPAWN,
	NUM_STATES
}
